format = """
$status\
$fill\
[](blue)\
$time\
$line_break\
$directory\
[](fg:pink)\
($git_branch\
$git_status\
[](grey)
)\
[](purple)\
$os\
$username\
[](fg:purple bg:teal)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:teal bg:cyan)\
$docker_context\
[ ](fg:cyan)
"""
# Blank line at the start of the prompt
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = '󰄾 '

# Set custom colour palette
palette = 'woody'

# Define custom colours
[palettes.woody]
# Forgrounds
default = '#00ff00'
dark = '#111111'
dark-grey = '#333333'
light = '#eeeeee'

# GH forgrounds
gh-success = '#0a4d00'
gh-warn = '#06637e'
gh-error = '#4d0000'

# Fire
fire-orange = '#f8630b'
fire-yellow = '#fff57b'

# Backgrounds
green = '#498a33'
grey = '#c0bbb9'
red = '#8a3333'
yellow = '#d3cf4c'
warn = '#700909'
purple = '#9A348E'
pink = '#DA627D'
salmon = '#FCA17D'
teal = '#86BBD8'
cyan = '#06969A'
blue = '#33658A'

[status]
style = 'bg:fire-yellow fg:dark'
success_symbol = '[ 󰸞 ](bg:green fg:light)[](green)'
symbol = ' 󱎘 '
not_executable_symbol = '  '
not_found_symbol = '  '
sigint_symbol = '  '
signal_symbol = ' 󱐋 '
format = "[$symbol($common_meaning$signal_name$maybe_int [ ](fg:fire-yellow bg:fire-orange)[](fire-orange))]($style)"
map_symbol = true
disabled = false

[time]
disabled = false
time_format = "%A %F %T" # Day ISO-Date Time Format
style = 'bg:blue fg:light'
format = '[ $time ]($style)'

[username]
show_always = true
style_user = "bg:purple"
style_root = "bg:warn fg:light"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:purple"
disabled = false # Disabled by default

# OS symbols override
[os.symbols]
Ubuntu = "  "

[directory]
style = "bg:pink fg:dark"
format = "[ $path]($style)[$read_only]($read_only_style)[ ]($style)"
# repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 0
truncation_symbol = "…/"
home_symbol = '󰜥'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents/" = "󰈙 /"
"Downloads/" = " /"
"Music/" = " /"
"Pictures/" = " /"
"dev/" = " /"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = "󰊢"
style = "bg:grey fg:dark"
format = '([](grey)[ $symbol $branch ]($style))'

[git_status]
style = "bg:grey fg:dark-grey"

format = '([(• $stashed$conflicted$untracked$deleted$renamed$modified$typechanged$staged)(• $ahead_behind )]($style))'
ahead = '[${count}󰛶](bg:grey fg:gh-warn)'
diverged = '[${ahead_count}󰛶󰲊 ${behind_count}󰛴󰲊](bg:grey fg:gh-error)'
behind = '[${count}󰛴](bg:grey fg:gh-warn)'
up_to_date = '[󰱔](bg:grey fg:gh-success)'

conflicted = '[${count}󰢪](bg:grey fg:gh-error) '
untracked = '${count}󰝒 '
stashed = '[${count}󱋡](bg:grey fg:gh-warn) '
modified = '[${count}󱇧](bg:grey fg:gh-warn) '
staged = '[${count}󰈖](bg:grey fg:gh-success) '
renamed = '[${count}󰾴](bg:grey fg:gh-warn) '
deleted = '[${count}󰮘](bg:grey fg:gh-error) '


# Environments
[c]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $sym fg:darkbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:teal fg:dark"
not_capable_style = "bg:teal fg:bold red"
format = '[ $symbol ($version)( 󰥼 $engines_version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:teal fg:dark"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:cyan fg:dark"
format = '[ $symbol $context ]($style)'

[fill]
symbol = ' '